name: Deploy-Code
on: 
  push:
    branches:
     - main
   
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: create zip bundle
        run: |
             cd function
             zip -r ../${{ github.sha }}.zip .
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
         name: zipped-bundle
         path: ${{ github.sha }}.zip

